version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
 test:
   docker:
     - image: circleci/python:3.7.5
   steps:
     - checkout
     - run: sudo make install
     - run: make lint
     - run: make tests
     - codecov/upload:
       file: 'coverage.xml'

workflows:
  version: 2
  test:
    jobs:
      - test
